data:
  dataset_name: humanact12
  path: /scratch/PHPSDataset/HumanAct12_256
  fid_file: /scratch/SyntheticData/humanact12128_inception_moments.npz
  img_size: 256
model:
  background_generator_kwargs:
    rgb_out_dim: 256
  bounding_box_generator_kwargs:
    scale_range_min: [0.3, 0.1, 0.1]
    scale_range_max: [0.5, 0.2, 0.2]
    translation_range_min: [-0.22, -0.12, 0.]
    translation_range_max: [0.22, 0.12, 0.]
  generator_kwargs:
    range_v: [0.41667, 0.5]
    fov: 10
  neural_renderer_kwargs:
    input_dim: 256
    n_feat: 256
  decoder_kwargs:
    rgb_out_dim: 256
training:
  visualize_every: 10
  out_dir:  /scratch1/out6
  learning_rate: 0.00025
