data:
  dataset_name: humanact12
  path: /scratch/PHPSDataset/HumanAct12_256
  fid_file: /scratch/SyntheticData/humanact12128_inception_moments.npz
  img_size: 256
model:
  background_generator_kwargs:
    rgb_out_dim: 256
  bounding_box_generator_kwargs:
    scale_range_min: [0.21, 0.21, 0.21]
    scale_range_max: [0.21, 0.21, 0.21]
    translation_range_min: [0, 0, 0.]
    translation_range_max: [0, 0, 0.]
  generator_kwargs:
    range_v: [0.5, 0.5]
    fov: 10
  neural_renderer_kwargs:
    input_dim: 256
    n_feat: 256
  decoder_kwargs:
    rgb_out_dim: 256
training:
  out_dir:  /scratch1/out4
  learning_rate: 0.00025
